[package]
name = "01_basic_ping_bot"
version = "0.1.0"
authors = ["my name <my@email.address>"]

[dependencies]
serenity = "0.5"
reqwest = "0.8.1"
html2runes = "1.0.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
html5ever = "0.13"
